setwd("C:/users/Chester/Desktop/Bonnie/data_mining")
install.packages("readxl")
library(readxl)

e_mtab_4040 <- read.table("E-MTAB-4040_clin_data.txt", header = TRUE, sep = "\t")
e_tabm_810 <- read_excel("E-TABM-810_clin_data.xlsx")
gse1477 <- read.table("GSE1477_clin_data.txt", header = TRUE, sep = "\t")
gse2109 <- read.table("GSE2109_clin_data.txt", header = TRUE, sep = "\t")
gse17155 <- read.table("GSE17155_clin_data.txt", header = TRUE, sep = "\t")
gse23891_gpl2879 <- read.table("GSE23891_GPL2879_clin_data.txt", header = TRUE, sep = "\t")
gse23891_gpl5477 <- read.table("GSE23891_GPL5477_clin_data.txt", header = TRUE, sep = "\t")
gse31259 <- read.table("GSE31259_clin_data.txt", header = TRUE, sep = "\t")
gse50512 <- read.table("GSE50512_clin_data.txt", header = TRUE, sep = "\t")
gse104730 <- read.table("GSE104730_clin_data.txt", header = TRUE, sep = "\t")
gse153636 <- read.table("GSE153636_clin_data.txt", header = TRUE, sep = "\t")
tcga_cell <- read.table("tcga_cell_clin_data.txt", header = TRUE, sep = "\t")
tcga_firehose <- read_excel("tcga_firehose_clin_data.xlsx")
tcga_mskcc <- read.table("tcga_mskcc_clin_data.txt", header = TRUE, sep = "\t")
tcga_nature <- read.table("tcga_nature_clin_data.txt", header = TRUE, sep = "\t")
tcga_pancan <- read.table("tcga_pancan_clin_data.txt", header = TRUE, sep = "\t")

head(e_mtab_4040)
head(e_tabm_810)
colnames(e_tabm_810)
